### ISSUE TITLE
포토북 UI 작업

### ISSUE THREAD

**Issue by haesol822** [HaruDamda/Picpic-FE#7]
# 포토북 UI 작업

## 목적

- 포토북 UI 작업

## To-do

- [x] 포토북에 넣을 사진 선택 뷰
- [x] 선택한 사진들 넘겨서 포토북 생성 뷰
- [x] 이모지 스티커 및 쪽지 남기기 기능 구현

## 기타 참고 사항

-
